// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.entropy.core.autogen.grpc.user;

public interface UserResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserResponses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .user.User user = 1;</code>
   */
  java.util.List<User>
      getUserList();
  /**
   * <code>repeated .user.User user = 1;</code>
   */
  User getUser(int index);
  /**
   * <code>repeated .user.User user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .user.User user = 1;</code>
   */
  java.util.List<? extends UserOrBuilder>
      getUserOrBuilderList();
  /**
   * <code>repeated .user.User user = 1;</code>
   */
  UserOrBuilder getUserOrBuilder(
      int index);
}
